### ISSUE TITLE
Revisar imagens e .md

### ISSUE THREAD

**Issue by hideraldoluis** [hideraldus13/roadmap-do-desenvolvedor-web#1]
- aviso.png
- intro.png
- frontend.png
- backend.png
- devops.png

- README.md
- colaborando.md

**Comment by oluys** [comment]
Hello.

I was checking at frontend.png, in the CSS Pre-processors I see you removed Less. Indeed, according to the original project, Less is not a very good option for someone beginning in 2019, BUT it's still an option. If your project aims to look an exact translation from the original one, maybe you should consider having all of its elements, even one like Less. Also notice that the black box description is missing information about Less, and why it shouldn't be considered as a first option.

**Comment by oluys** [comment]
Still on frontend.png, you have a typo. At 'Arquiteturas de CSS', in the black box, the word 'Entretando' is wrong. It should be 'Entretanto'.

**Comment by hideraldoluis** [comment]
> Hello.
> 
> I was checking at frontend.png, in the CSS Pre-processors I see you removed Less. Indeed, according to the original project, Less is not a very good option for someone beginning in 2019, BUT it's still an option. If your project aims to look an exact translation from the original one, maybe you should consider having all of its elements, even one like Less. Also notice that the black box description is missing information about Less, and why it shouldn't be considered as a first option.

Yes. It's not a exact translation from the original. I made a lot of changes considering our region (people and companies) and, of course, my opinion. 😄 Feel free to open a Issue which a change to initiate a discussion. 🤗

**Comment by hideraldoluis** [comment]
> Still on frontend.png, you have a typo. At 'Arquiteturas de CSS', in the black box, the word 'Entretando' is wrong. It should be 'Entretanto'.

Done! Thanks.
